In [2]:
import pandas as pd
from scipy import stats
import matplotlib as plt
import seaborn as sn
import numpy as np

###   Q.1   A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

### Ans.- As two samples given are continuous variables (Numeric data), here we can use individual sample "t- test", Considering following null and alternate hypothesis

### H0= There is no difference in diameters(d1=d2)
### H1= There is difference in diameters(d1!=d2)


In [3]:
cutlet = pd.read_csv("D:\pyt\Assignment\Assignment 3-Hypothesis Testing\Cutlets.csv") #loading data set

In [4]:
cutlet.head()  

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [5]:
unit_A= cutlet.iloc[:,0] #for comparison, we are creating two arrays unit_A & unit_B using iloc fucntion

In [6]:
unit_B=cutlet.iloc[:,1]

In [7]:
stat_value, p_value =np.round(stats.ttest_ind(unit_A,unit_B),4)
print(f"Statistical value is {stat_value}")
print(f"p value is {p_value}")

Statistical value is 0.7229
p value is 0.4722


In [8]:
alpha = 0.05 # significance value given in problem statement 

In [9]:
if p_value < alpha:
    print("We reject the null hypothesis")        # reject null (H0) and accept the aleternate (H1) hypothesis
    print("There is significant difference between the diameter")
else:
    print("We fail to reject the null hypothesis") # accept null (H0) and reject the aleternate (H1) hypothesis
    print("There is no significant difference between the diameter")

We fail to reject the null hypothesis
There is no significant difference between the diameter


### Q. 2 A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch. Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

### Ans.:- Here 4 samples are given in numeric form(continuous variable) i.e. 4 continuous variables. Hence we are going to use "ANOVO test"

### H0= TAT for all labs are same (lab1=lab2=lab3=lab4)
### H1= TAT for all labs are not same (lab1 != lab2 != lab3 != lab4)


In [10]:
tat=pd.read_csv("D:\pyt\Assignment\Assignment 3-Hypothesis Testing\LabTAT.csv")

In [11]:
tat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [12]:
lab_1=tat.iloc[:,0]
lab_2=tat.iloc[:,1]
lab_3=tat.iloc[:,2]
lab_4=tat.iloc[:,3]

In [13]:
stat_val1, p_val1=stats.f_oneway(lab_1,lab_2,lab_3,lab_4)
print(f"Statistical value is {(stat_val1)}")
print(f"p value is {p_val1}")

Statistical value is 118.70421654401437
p value is 2.1156708949992414e-57


In [14]:
alpha = 0.05 # significance value given in problem statement 

In [15]:
if p_val1 < alpha:
    print("We reject the null hypothesis")           # reject null (H0) and accept the aleternate (H1) hypothesis
    print("TAT's for all labs are not same")
else:
    print("We fail to reject the null hypothesis")    # accept null (H0) and reject the aleternate (H1) hypothesis
    print("There is no significant difference between the diameter")

We reject the null hypothesis
TAT's for all labs are not same


### Q.3 Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

### Ans.:- As This is catagorical data, we will perfrom chi-square test for independance( as the data we are testing is independant), Chi-square goodness of fit test is performed when we are comparing the data with population.

### H0= all proportions are equal
### H1= all proportions are not equal

In [16]:
buyer_ratio=pd.read_csv("D:\pyt\Assignment\Assignment 3-Hypothesis Testing\BuyerRatio.csv")

In [17]:
buyer_ratio.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [22]:
# Separating males and females from given file as given files also have "str" hance can not be directly sullpied to chi function
males=buyer_ratio.iloc[0,1:]
females=buyer_ratio.iloc[1,1:]

In [30]:
buyer=[males,females]    # making the table
print(buyer)

[East      50
West     142
North    131
South     70
Name: 0, dtype: object, East      435
West     1523
North    1356
South     750
Name: 1, dtype: object]


In [41]:
stat=stats.chi2_contingency(buyer)

In [43]:
# first value in output at zero index is chi-square value, value at first index is p_value,
# value at second index is df(degrees of freedom), and finally at third index we have table of expected values 
stat       

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [45]:
chi_stat= stat[0]
chi_stat

1.595945538661058

In [46]:
p_valu= stat[1]
p_valu

0.6603094907091882

In [47]:
deg_free =stat[2]
deg_free

3

In [48]:
expeted_val =stat[3]
expeted_val

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [64]:
alpha=0.05
if p_valu < alpha:
    print("We reject the null hypothesis")           # reject null (H0) and accept the aleternate (H1) hypothesis
    print("All Proportions are not equal")
else:
    print("We fail to reject the null hypothesis")    # accept null (H0) and reject the aleternate (H1) hypothesis
    print("All Proprtions are equal")

We fail to reject the null hypothesis
All Proprtions are equal


In [66]:
stats.contingency.expected_freq(buyer)           # To calculate expected values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

###  Same thing calculated below by manual calculations(Alternate method)

In [88]:
chi_sq= sum([(o-e)**2/e for o,e in zip (buyer,expeted_val)]) # Zip is used because of matrix
chi_sq

East      1.34226
West     0.173035
North    0.000116
South    0.080534
dtype: object

In [85]:
# output of above are 4 rows, hence adding these
chi_squ=chi_sq[0]+chi_sq[1]+chi_sq[2]+chi_sq[3]
chi_squ

1.5959455386610577

In [86]:
critical_val=stats.chi2.ppf(0.95,deg_free) # cirital value at 5 % significance level
critical_val

7.814727903251179

In [89]:
p_value12= 1-stats.chi2.cdf(chi_squ,df=3)  
p_value12

0.6603094907091882

In [90]:
if chi_squ >= critical_val:
    print("Reject the null")
else:
    print("Fail to reject null")

Fail to reject null


### Q.4 TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

### Ans.:- Here data given is catogorical data hence we will use chi-square test of independance 

### H0= defective % are same for all centers
### H1= defective % are not same for all centers

In [91]:
df=pd.read_csv("D:\pyt\Assignment\Assignment 3-Hypothesis Testing\Costomer+OrderForm.csv")

In [92]:
df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [102]:
phil=df.Phillippines.value_counts()
indo=df.Indonesia.value_counts()
malta=df.Malta.value_counts()
india=df.India.value_counts()

In [103]:
phil.values
indo.values
malta.values
india.values

array([280,  20], dtype=int64)

In [105]:
df_1=[phil.values[0],indo.values[0],malta.values[0],india.values[0]]
df_2=[phil.values[1],indo.values[1],malta.values[1],india.values[1]]
data=[df_1,df_2]

In [106]:
data

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [108]:
results=stats.chi2_contingency(data)

In [110]:
p_value1=results[1]
p_value1

0.2771020991233135

In [111]:
alpha=0.05
if p_value1 < alpha:
    print("We reject the null hypothesis")           # reject null (H0) and accept the aleternate (H1) hypothesis
    print("All Proportions are not equal")
else:
    print("We fail to reject the null hypothesis")    # accept null (H0) and reject the aleternate (H1) hypothesis
    print("All Proprtions are equal")

We fail to reject the null hypothesis
All Proprtions are equal
